const ICON_MAP = {
  bountyhunterhunter: "Bounty Hunter - Hunter",
  bountyhunterrogue: "Bounty Hunter - Rogue",
  bountyhunterlegacyhunter: "Bounty Hunter (Legacy) - Hunter",
  bountyhunterlegacyrogue: "Bounty Hunter (Legacy) - Rogue",
  cluescrollsall: "Clue Scrolls (all)",
  cluescrollsbeginner: "Clue Scrolls (beginner)",
  cluescrollseasy: "Clue Scrolls (easy)",
  cluescrollsmedium: "Clue Scrolls (medium)",
  cluescrollshard: "Clue Scrolls (hard)",
  cluescrollselite: "Clue Scrolls (elite)",
  cluescrollsmaster: "Clue Scrolls (master)",
  lmsrank: "LMS - Rank",
  pvparenarank: "PvP Arena - Rank",
  soulwarszeal: "Soul Wars Zeal",
  riftsclosed: "Rifts Closed",
  colosseumglory: "Colosseum Glory",
  collectionslogged: "Collections Logged",
  abyssalsire: "Abyssal Sire",
  alchemicalhydra: "Alchemical Hydra",
  amoxliatl: "Amoxliatl",
  araxxor: "Araxxor",
  artio: "Artio",
  barrowschests: "Barrows Chests",
  bryophyta: "Bryophyta",
  callisto: "Callisto",
  calvarion: "Calvarion",
  cerberus: "Cerberus",
  chambersofxeric: "Chambers of Xeric",
  chambersofxericchallengemode: "Chambers of Xeric: Challenge Mode",
  chaoselemental: "Chaos Elemental",
  chaosfanatic: "Chaos Fanatic",
  commanderzilyana: "Commander Zilyana",
  corporealbeast: "Corporeal Beast",
  crazyarchaeologist: "Crazy Archaeologist",
  dagannothprime: "Dagannoth Prime",
  dagannothrex: "Dagannoth Rex",
  dagannothsupreme: "Dagannoth Supreme",
  derangedarchaeologist: "Deranged Archaeologist",
  dukesucellus: "Duke Sucellus",
  generalgraardor: "General Graardor",
  giantmole: "Giant Mole",
  grotesqueguardians: "Grotesque Guardians",
  hespori: "Hespori",
  kalphitequeen: "Kalphite Queen",
  kingblackdragon: "King Black Dragon",
  kraken: "Kraken",
  kreearra: "Kree'arra",
  kriltsutsaroth: "Kril'tsutsaroth",
  lunarchests: "Lunar Chests",
  mimic: "Mimic",
  nex: "Nex",
  nightmare: "Nightmare",
  phosanisnightmare: "Phosani's Nightmare",
  obor: "Obor",
  phantommuspah: "Phantom Muspah",
  sarachnis: "Sarachnis",
  scorpia: "Scorpia",
  scurrius: "Scurrius",
  skotizo: "Skotizo",
  solheredit: "Sol Heredit",
  spindel: "Spindel",
  tempoross: "Tempoross",
  thegauntlet: "The Gauntlet",
  theroyaltitans: "The Royal Titans",
  thecorruptedgauntlet: "The Corrupted Gauntlet",
  thehueycoatl: "The Hueycoatl",
  theleviathan: "The Leviathan",
  thewhisperer: "The Whisperer",
  theatreofblood: "Theatre of Blood",
  theatreofbloodhardmode: "Theatre of Blood: Hard Mode",
  thermonuclearsmokedevil: "Thermonuclear Smoke Devil",
  tombsofamascut: "Tombs of Amascut",
  tombsofamascutexpertmode: "Tombs of Amascut: Expert Mode",
  tzkalzuk: "TzKal-Zuk",
  tztokjad: "TzTok-Jad",
  vardorvis: "Vardorvis",
  venenatis: "Venenatis",
  vetion: "Vet'ion",
  vorkath: "Vorkath",
  wintertodt: "Wintertodt",
  yama: "Yama",
  zalcano: "Zalcano",
  zulrah: "Zulrah",
};

export default ICON_MAP;
